const express = require("express");
const isAuth = require("../../../middlewares/isAuth");
const isAdmin = require("../../../middlewares/isAdmin");
const salesReport = require("../../../controllers/admin/reports/salesReport");
const getCustomerList = require("../../../controllers/admin/reports/getCustomerList");
const getSingleCustomer = require("../../../controllers/admin/reports/getSingleCustomer");
const router = express.Router();
router.get("/sale", isAuth, isAdmin, salesReport);
router.get("/customer/list", isAuth, isAdmin, getCustomerList);
router.get("/customer/single", isAuth, isAdmin, getSingleCustomer);
module.exports = router;
